csvselectrow: Handle user ESC from dialog

diff --git a/bin/csvselectrow b/bin/csvselectrow
--- a/bin/csvselectrow
+++ b/bin/csvselectrow
@@ -107,12 +107,19 @@ fi
 < "$tmpdir/input.csv" csvsort -I -l > "$tmpdir/input_numbered.csv"
 
 function do_line_based {
-    < "$tmpdir/input_numbered.csv" sed -E '1 s/^line_number(.*)$/ROW NUMBER\1/' | csvlook -I >> /dev/stderr
+  < "$tmpdir/input_numbered.csv" sed -E '1 s/^line_number(.*)$/ROW NUMBER\1/' | csvlook -I >> /dev/stderr
+  while : ; do
     echo -n "Select row number (press enter to abort selection): " >> /dev/stderr
     read -r num
     if [ "$num" = '' ]; then
       exit 2
     fi
+    if [ "$num" -gt "$rowcount" ]; then
+      echo "Invalid number $num, try again." >> /dev/stderr
+      continue
+    fi
+    break
+  done
 }
 
 
@@ -126,6 +133,10 @@ if [ "$INTERACTIVE" = true ]; then
   num="$((dialog --column-separator '|' --menu "Choose one:" -1 -1 3 --file "$tmpdir/dialog_input.txt" 2>"$tmpdir/dialog_choice.txt" 2>&4 1>&3) 4>&1 3>&2)"
   exitcode=$?
   tput reset 1>&2
+  if [ "$exitcode" = 255 ]; then # User pressed ESC
+    exit 2
+  fi
+
   if [ "$exitcode" != '0' ] && [ "$exitcode" != '1' ]; then
     echo "'dialog' exited with error code $exitcode, falling back on line-based selection mode." >> /dev/stderr
     sleep 1
