Various updates

diff --git a/bin/csvselectrow b/bin/csvselectrow
--- a/bin/csvselectrow
+++ b/bin/csvselectrow
@@ -1,13 +1,100 @@
 #!/bin/bash
-inputfile=$1
+#set -euo pipefail
 
-if [ "$inputfile" = '' ]; then
-  echo "Error: got no input file"
+function failure {
+  local lineno=$1
+  local msg=$2
+  echo "Failed at $lineno: $msg" 1>&2
+}
+trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
+
+VERSION="0.1.0"
+PROGRAMNAME="csvselectrow"
+
+
+function print_help {
+  echo "\
+$PROGRAMNAME $VERSION
+Martijn Heil <m.heil375@gmail.com>
+Copyright (c) 2021 Martijn Heil
+
+Get value of first CSV row based on column name.
+Input should be passed to stdin looking like this:
+<HEADER> (newline)
+<DATA ROW TO GET VALUE FROM> (newline) ...
+
+USAGE:
+    $PROGRAMNAME [FLAGS] [OPTIONS] <FILE>
+
+FLAGS:
+    -h, --help        Prints help information
+    -v, --version     Prints version information
+    -i, --interactive Use a interactive dialog."
+}
+
+function print_version {
+  echo "$PROGRAMNAME v$VERSION"
+}
+
+# Check if enhanced getopt is available
+! getopt --test > /dev/null
+if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
+  echo "I'm sorry, `getopt --test` failed in this environment." >> /dev/stderr
+  echo "This probably means that there is no enhanced getopt available." >> /dev/stderr
   exit 1
 fi
 
+OPTIONS=:n:i:d:h:v
+LONGOPTS=:name:,index:,delim:,help,version
+
+! PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
+if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+  exit 2
+fi
+
+eval set -- "$PARSED"
+# bounding polygon in Well Known Text (WKT), de coordinaten in RD
+INTERACTIVE=false
+
+while true; do
+  case "$1" in
+    -i|--interactive)
+    INTERACTIVE=true
+    ;;
+
+    -h|--help)
+    print_help
+    exit 0
+    ;;
+
+    -v|--version)
+    print_version
+    exit 0
+    ;;
+
+    --)
+    shift
+    break
+    ;;
+
+    *)
+    break
+    #echo "Programming error" >> /dev/stderr
+    #exit 3
+    ;;
+  esac
+  shift
+done
+
+shift $(($OPTIND - 1))
+
 tmpdir="$(mktemp -d)"
 
+function cleanup {
+  rm -rf "$tmpdir"
+}
+
+trap cleanup EXIT
 cp "$1" "$tmpdir/input.csv"
 
 rowcount=$(< "$tmpdir/input.csv" csvrowcount)
@@ -18,15 +105,38 @@ if [ "$rowcount" -le "1" ]; then
 fi
 
 < "$tmpdir/input.csv" csvsort -I -l > "$tmpdir/input_numbered.csv"
-< "$tmpdir/input_numbered.csv" sed -E '1 s/^line_number(.*)$/ROW NUMBER\1/' | csvlook -I >> /dev/stderr
 
-echo -n "Select row number (press enter to abort selection): " >> /dev/stderr
-read -r num
-if [ "$num" = '' ]; then
-  rm -rf "$tmpdir"
-  exit 2
+function do_line_based {
+    < "$tmpdir/input_numbered.csv" sed -E '1 s/^line_number(.*)$/ROW NUMBER\1/' | csvlook -I >> /dev/stderr
+    echo -n "Select row number (press enter to abort selection): " >> /dev/stderr
+    read -r num
+    if [ "$num" = '' ]; then
+      exit 2
+    fi
+}
+
+
+if [ "$INTERACTIVE" = true ]; then
+  # dialog doesn't like double quotes in the data.. as this is only for display to the user,
+  # we replace all double quotes with two single quotes, as it looks somewhat similar and hopefully gets the intent across.
+  < "$tmpdir/input_numbered.csv" csv2nix | tail -n +2 | sed "s/\"/''/g" | sed -E 's/^([0-9]*)(.*)$/\1 "\2"/' | sed -E 's/,/| /g' | csvquote -u > "$tmpdir/dialog_input.txt"
+
+  # Awesome redirection hackery, it works!
+  # Ignore the strange syntax highlighting.. it's valid anyhow
+  num="$((dialog --column-separator '|' --menu "Choose one:" -1 -1 3 --file "$tmpdir/dialog_input.txt" 2>"$tmpdir/dialog_choice.txt" 2>&4 1>&3) 4>&1 3>&2)"
+  exitcode=$?
+  tput reset 1>&2
+  if [ "$exitcode" != '0' ] && [ "$exitcode" != '1' ]; then
+    echo "'dialog' exited with error code $exitcode, falling back on line-based selection mode." >> /dev/stderr
+    sleep 1
+    do_line_based
+  fi
+
+  if [ "$num" == '' ]; then
+    exit 2
+  fi
+else
+  do_line_based
 fi
 
 < "$tmpdir/input_numbered.csv" csvgrep -c "line_number" -r "^$num\$" | csvcut --not-columns 1
-
-rm -rf "$tmpdir"
diff --git a/bin/forproduct b/bin/forproduct
--- a/bin/forproduct
+++ b/bin/forproduct
@@ -1,4 +1,6 @@
 #!/bin/bash
+#set -euo pipefail -o functrace
+
 csvfile="$1"
 barcode_column="$2"
 delim="$3"
@@ -21,6 +23,13 @@ function cleanup {
 
 trap cleanup EXIT
 
+function failure {
+  local lineno=$1
+  local msg=$2
+  echo "Failed at $lineno: $msg" 1>&2
+}
+#trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
+
 # We re-populate our tempdir with generated data whenever the original CSV file changes.
 cat << 'EOF' > "$tempexecutable"
 #!/bin/bash
@@ -37,7 +46,6 @@ bash -c "$tempexecutable \"\$@\"" "null" "$csvfile" "$barcode_column" "$tempdir"
 inotify_exec_on_file_change "$csvfile" bash -c "$tempexecutable \"\$@\"" "null" "$csvfile" "$barcode_column" "$tempdir" &> /dev/null &
 
 
-
 function do_barcode_search {
   echo -n "Enter barcode (press enter to go to manual search): "
   read -r barcode
@@ -51,6 +59,7 @@ function do_barcode_search {
   if [ "$resultcount" -le "0" ]; then
     return 1
   fi
+
   return 0
 }
 
@@ -65,6 +74,15 @@ function do_manual_search {
     # (?i) is regex flag for case insensivity
     results=$(< "$csvfile" csvgrep -d "$delim" -r "(?i)$query" -c "$searchable_columns" -a)
     resultcount=$(echo "$results" | csvrowcount)
+
+    if [ "$resultcount" -gt "1000" ]; then
+      echo -n "Got $resultcount results. Are you sure you want to view them all? [y/N]"
+      read -r query
+      if [ "$query" != "Y" ] && [ "$query" != "y" ]; then
+        return 1
+      fi
+    fi
+
     echo "Got $resultcount results."
     if [ "$resultcount" = "0" ]; then
       continue
@@ -75,6 +93,9 @@ function do_manual_search {
 
 while :
 do
+  # Need to declare this or else it will complain about unbound variables
+  results=''
+
   echo -e '\a'
   do_barcode_search
   do_barcode_search_result=$?
@@ -95,7 +116,7 @@ do
     continue
   fi
 
-  result=$(csvselectrow <(echo "$results"))
+  result="$(csvselectrow -i <(echo "$results"))"
   csvselectresult=$?
   if [ $csvselectresult -eq 2 ]; then # aborted
     echo "Aborted selection."
